version: "3"
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3001:3001"

    api:
        build:
            context: ./api
        ports:
            - "3000:3000"
